const data = [
  {
    key: "01",
    name: "long beach suites",
    rent: 8622,
    star: "4",
    location: "Dhaka",
    img1: "https://i.ibb.co/Tm8nL8M/ex1.jpg",
    img2: "https://i.ibb.co/5Tg8zRf/bedroom-01.jpg",
    img3: "https://i.ibb.co/hBvx5Cz/Lobby-1.jpg",
    img4: "https://i.ibb.co/YjsJ5pv/W1.jpg",
  },
  {
    key: "02",
    name: "Hotel Rahmania",
    rent: 2300,
    star: "3",
    location: "Dhaka",
    img1: "https://i.ibb.co/PGd0KVM/ex2.jpg",
    img2: "https://i.ibb.co/jDYRShL/bedroom-02.jpg",
    img3: "https://i.ibb.co/2ZSRFD4/Lobby-2.jpg",
    img4: "https://i.ibb.co/YjsJ5pv/W1.jpg",
  },
  {
    key: "03",
    name: "Hotel Diamond Park",
    rent: 5550,
    star: "4",
    location: "Dhaka",
    img1: "https://i.ibb.co/9pQjKRf/ex3.jpg",
    img2: "https://i.ibb.co/hVx1Yj9/Bedroom-3.jpg",
    img3: "https://i.ibb.co/cc9WmnC/Lobby-3.jpg",
    img4: "https://i.ibb.co/QYd435Q/W3.jpg",
  },
  {
    key: "04",
    name: "Hotel Blue Bird",
    rent: 2917,
    star: "3",
    location: "Sylhet",
    img1: "https://i.ibb.co/jzymKkS/ex4.jpg",
    img2: "https://i.ibb.co/xj5nTGW/Bedroom-04.jpg",
    img3: "https://i.ibb.co/k0JWfnp/Lobby-4.jpg",
    img4: "https://i.ibb.co/WypWsKT/W4.jpg",
  },
  {
    key: "05",
    name: "Hotel Fountain",
    rent: 4552,
    star: "4",
    location: "Narayanganj",
    img1: "https://i.ibb.co/LZLHbMw/ex5.jpg",
    img2: "https://i.ibb.co/Bf7vf9P/Bedroom-05.jpg",
    img3: "https://i.ibb.co/nmhRpyK/Lobby-5.jpg",
    img4: "https://i.ibb.co/nmhRpyK/Lobby-5.jpg",
  },
  {
    key: "06",
    name: "Hotel City Palace",
    rent: 1708,
    star: "2",
    location: " Jamalpur",
    img1: "https://i.ibb.co/BBCqPc7/ex6.jpg",
    img2: "https://i.ibb.co/JCjpGqv/Bedroom-06.jpg",
    img3: "https://i.ibb.co/YfRpXpr/Lobby-06.jpg",
    img4: "https://i.ibb.co/wQLDWVQ/W6.jpg",
  },
  {
    key: "07",
    name: "Renaissance Hotel",
    rent: 117899,
    star: "5",
    location: "Dhaka",
    img1: "https://i.ibb.co/wrT55jk/ex7.jpg",
    img2: "https://i.ibb.co/MNN84fK/Bedroom-07.jpg",
    img3: "https://i.ibb.co/0KCt8db/Lobby-7.jpg",
    img4: "https://i.ibb.co/xSRvPjg/W7.jpg",
  },
  {
    key: "08",
    name: "The Grand Hotel",
    rent: 2500,
    star: "3",
    location: "Khulna",
    img1: "https://i.ibb.co/fY2Dwf6/ex8.jpg",
    img2: "https://i.ibb.co/1TJYVrn/Bedroom-08.jpg",
    img3: "https://i.ibb.co/qJ80vPn/Lobby-8.jpg",
    img4: "https://i.ibb.co/2FhhZQm/W8.jpg",
  },
  {
    key: "09",
    name: "Hotel71",
    rent: 3742,
    star: "3",
    location: "Bogura",
    img1: "https://i.ibb.co/bRF32VC/ex9.jpg",
    img2: "https://i.ibb.co/3dVjQ3F/Bedroom-09.jpg",
    img3: "https://i.ibb.co/3c4sV14/Lobby-9.jpg",
    img4: "https://i.ibb.co/WHTHWdC/W9.jpg",
  },
];
